/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import BaseDatos.Conexion;
import java.sql.ResultSet;

/**
 *
 * @author landr
 */
public class MenuAdmin extends javax.swing.JFrame {

    int privilegio;
    int DNI;
    String nombre;

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        
        this.setExtendedState(NORMAL);
    }

    public String LoginDoctor(int DNI) {
        System.out.println("Mostrando Datos");
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT NOMBRE FROM DOCTOR WHERE DNI = %d", DNI);
        try {
            ResultSet resultado = objConexion.consultarRegistros(strSentenciaInsert);
            if (resultado.getString("NOMBRE") != null) {
                nombre = resultado.getString("NOMBRE");
            } else {
                nombre = null;
            }
        } catch (Exception e) {
        }

        return nombre;
    }

    public String LoginPaciente(int DNI) {
        System.out.println("Mostrando Datos");
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT NOMBRE FROM PACIENTE WHERE DNI = %d", DNI);
        try {
            ResultSet resultado = objConexion.consultarRegistros(strSentenciaInsert);
            if (resultado.getString("NOMBRE") != null) {
                nombre = resultado.getString("NOMBRE");
            } else {
                nombre = null;
            }
        } catch (Exception e) {
        }

        return nombre;
    }

    public String LoginSecretaria(int DNI) {
        System.out.println("Mostrando Datos");
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT NOMBRE FROM SECRETARIA WHERE DNI = %d", DNI);
        try {
            ResultSet resultado = objConexion.consultarRegistros(strSentenciaInsert);
            if (resultado.getString("NOMBRE") != null) {
                nombre = resultado.getString("NOMBRE");
            } else {
                nombre = null;
            }
        } catch (Exception e) {
        }

        return nombre;
    }

    public MenuAdmin(int privilegio, int DNI) {
        initComponents();
        //  this.setExtendedState(MAXIMIZED_BOTH); --maximiza la ventaza

        this.privilegio = privilegio;
        this.DNI = DNI;
        if (LoginDoctor(this.DNI) != null) {
            nombre = LoginDoctor(this.DNI);
        } else if (LoginPaciente(this.DNI) != null) {
            nombre = LoginPaciente(this.DNI);
        } else {
            nombre = LoginSecretaria(this.DNI);
        }
        switch (this.privilegio) {
            case 1: {
                btnCita.setVisible(true);
                btnConsultorio.setVisible(false);
                btnDoctor.setVisible(false);
                btnHistorial.setVisible(true);
                btnHorario.setVisible(false);
                btnPaciente.setVisible(false);
                btnSecretaria.setVisible(false);
                txtUsuario.setText(nombre);
                break;
            }
            case 2: {
                btnCita.setVisible(true);
                btnConsultorio.setVisible(false);
                btnDoctor.setVisible(true);
                btnHistorial.setVisible(true);
                btnHorario.setVisible(true);
                btnPaciente.setVisible(true);
                btnSecretaria.setVisible(false);
                txtUsuario.setText(nombre);
                break;
            }
            case 3: {
                txtUsuario.setText(nombre);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRetornar = new javax.swing.JButton();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();
        btnSecretaria = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        btnConsultorio = new javax.swing.JButton();
        btnCita = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jLabel8.setText("-");

        jLabel9.setText("X");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetornar.setBackground(new java.awt.Color(0, 0, 102));
        btnRetornar.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnRetornar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetornar.setText("Cerrar Sesion");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 20, 30));

        pnlTitulo.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Menu");
        pnlTitulo.add(jLabel1);

        jPanel1.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 460, 90));

        btnHistorial.setBackground(new java.awt.Color(0, 0, 102));
        btnHistorial.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 210, -1));

        btnPaciente.setBackground(new java.awt.Color(0, 0, 102));
        btnPaciente.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnPaciente.setText("Registro Paciente");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 440, -1));

        btnSecretaria.setBackground(new java.awt.Color(0, 0, 102));
        btnSecretaria.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        btnSecretaria.setText("Registro Secretaria");
        btnSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecretariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 440, -1));

        btnDoctor.setBackground(new java.awt.Color(0, 0, 102));
        btnDoctor.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctor.setText("Registro Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 440, -1));

        btnHorario.setBackground(new java.awt.Color(0, 0, 102));
        btnHorario.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnHorario.setText("Horarios");
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, -1));

        btnConsultorio.setBackground(new java.awt.Color(0, 0, 102));
        btnConsultorio.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultorio.setText("Consultorios");
        btnConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultorioActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 320, 210, -1));

        btnCita.setBackground(new java.awt.Color(0, 0, 102));
        btnCita.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnCita.setForeground(new java.awt.Color(255, 255, 255));
        btnCita.setText("Cita");
        btnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, -1));

        txtUsuario.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        txtUsuario.setText("USUARIO");
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        Fondo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaActionPerformed
        Cita abrir = new Cita();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCitaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        Historial abrir = new Historial();
        abrir.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        Registro_Doctor abrir = new Registro_Doctor(this.privilegio, this.DNI);
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        Registro_Paciente abrir = new Registro_Paciente();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecretariaActionPerformed
        Registro_Secretaria abrir = new Registro_Secretaria();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSecretariaActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        Horarios abrir = new Horarios();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        Login abrir = new Login();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnConsultorio;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JButton btnSecretaria;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
